import { useState, useRef } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useResumeContext } from "@/contexts/ResumeContext";
import ResumeUpload from "@/components/ResumeUpload";
import { readResumeAsText } from "@/lib/extractPdf";
import LoadingSpinner from "@/components/LoadingSpinner";
import ScoreCard from "@/components/ScoreCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ArrowRight, Home, MessageSquare, Download } from "lucide-react";
import { toast } from "sonner";

interface AnalysisResult {
  atsScore: number;
  skillMatchPercentage: number;
  matchedSkills: string[];
  missingSkills: string[];
  grammarIssues: number;
  toneAnalysis: string;
  suggestions: string[];
  marketDemand: string;
}

const ResumeAnalyzer = () => {
  const { setResumeText, setJobRole: setCtxJobRole, setMatchedSkills, setMissingSkills } = useResumeContext();
  const [file, setFile] = useState<File | null>(null);
  const [jobRole, setJobRole] = useState("");
  const [jobDescription, setJobDescription] = useState("");
  const [inputMode, setInputMode] = useState<"role" | "description">("role");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleAnalyze = async () => {
    if (!file) return toast.error("Please upload your resume first");
    if (inputMode === "role" && !jobRole) return toast.error("Please enter a job role");
    if (inputMode === "description" && !jobDescription) return toast.error("Please enter a job description");

    setLoading(true);
    setResult(null);

    try {
      const parsed = await readResumeAsText(file);
      const { data, error } = await supabase.functions.invoke("analyze-resume", {
        body: {
          ...(parsed.base64 ? { resumeBase64: parsed.base64 } : { resumeText: parsed.text }),
          jobRole: inputMode === "role" ? jobRole : undefined,
          jobDescription: inputMode === "description" ? jobDescription : undefined,
        },
      });

      if (error) {
        const errorBody = typeof error === "object" && "message" in error ? error.message : String(error);
        throw new Error(errorBody);
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      setResult(data.analysis);
      // Store in context for downstream pages
      setResumeText(parsed.text || "");
      setCtxJobRole(inputMode === "role" ? jobRole : "Target Role");
      setMatchedSkills(data.analysis.matchedSkills || []);
      setMissingSkills(data.analysis.missingSkills || []);
    } catch (err: Error | unknown) {
      const error = err instanceof Error ? err : new Error(String(err));
      console.error(error);
      toast.error(error.message || "Failed to analyze resume");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    const role = inputMode === "role" ? jobRole : "Target Role";
    const report = `
═══════════════════════════════════════════════════
           RESUME ANALYSIS REPORT
═══════════════════════════════════════════════════

Target Role: ${role}
Generated: ${new Date().toLocaleString()}

───────────────────────────────────────────────────
  SCORES
───────────────────────────────────────────────────

  ATS Compatibility Score:    ${result.atsScore}%
  Skill Match Percentage:     ${result.skillMatchPercentage}%
  Grammar Issues Found:       ${result.grammarIssues}
  Resume Tone:                ${result.toneAnalysis}

───────────────────────────────────────────────────
  MATCHED SKILLS
───────────────────────────────────────────────────

${result.matchedSkills.map((s) => `  ✓ ${s}`).join("\n")}

───────────────────────────────────────────────────
  MISSING SKILLS (Gap Areas)
───────────────────────────────────────────────────

${result.missingSkills.map((s) => `  ✗ ${s}`).join("\n")}

───────────────────────────────────────────────────
  MARKET DEMAND ANALYSIS
───────────────────────────────────────────────────

${result.marketDemand}

───────────────────────────────────────────────────
  IMPROVEMENT SUGGESTIONS
───────────────────────────────────────────────────

${result.suggestions.map((s, i) => `  ${i + 1}. ${s}`).join("\n")}

═══════════════════════════════════════════════════
  Generated by ResumeAI — AI-Based Assessment System
═══════════════════════════════════════════════════
`.trim();

    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Resume_Analysis_Report_${role.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  return (
    <div className="min-h-screen">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-8 animate-fade-in">
          <span className="font-mono text-[11px] text-primary uppercase tracking-widest block mb-2">
            Module 02
          </span>
          <h1 className="text-3xl font-medium tracking-tight mb-2">Resume Analyzer</h1>
          <p className="text-muted-foreground">
            Upload your resume with a job role or description for comprehensive AI analysis.
          </p>
        </div>

        {!result && (
          <div className="space-y-6 animate-slide-up">
            <ResumeUpload
              onFileSelect={setFile}
              selectedFile={file}
              onClear={() => {
                setFile(null);
                setResult(null);
              }}
            />

            <div className="flex gap-2">
              <button
                onClick={() => setInputMode("role")}
                className={`px-4 py-2 text-sm rounded-md transition-colors ${
                  inputMode === "role"
                    ? "bg-foreground text-background"
                    : "bg-secondary text-muted-foreground hover:text-foreground"
                }`}
              >
                Job Role
              </button>
              <button
                onClick={() => setInputMode("description")}
                className={`px-4 py-2 text-sm rounded-md transition-colors ${
                  inputMode === "description"
                    ? "bg-foreground text-background"
                    : "bg-secondary text-muted-foreground hover:text-foreground"
                }`}
              >
                Job Description
              </button>
            </div>

            {inputMode === "role" ? (
              <Input
                placeholder="Enter target job role (e.g., Data Analyst, Full Stack Developer)"
                value={jobRole}
                onChange={(e) => setJobRole(e.target.value)}
                className="h-12"
              />
            ) : (
              <Textarea
                placeholder="Paste the job description here..."
                value={jobDescription}
                onChange={(e) => setJobDescription(e.target.value)}
                className="min-h-[120px]"
              />
            )}

            <Button
              onClick={handleAnalyze}
              disabled={!file || loading}
              className="w-full h-12 rounded-lg gap-2"
            >
              Analyze Resume
              <ArrowRight className="size-4" />
            </Button>

            <Link to="/">
              <Button variant="outline" className="gap-2 mt-2">
                <Home className="size-4" />
                Home
              </Button>
            </Link>
          </div>
        )}

        {loading && <LoadingSpinner message="Validating resume and running analysis..." />}

        {result && (
          <div ref={reportRef} className="mt-2 space-y-8 animate-fade-in">
            {/* Scores */}
            <div>
              <h2 className="font-mono text-[11px] text-primary uppercase tracking-widest mb-4">
                Analysis Scores
              </h2>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <ScoreCard label="ATS Score" value={result.atsScore} suffix="%" />
                <ScoreCard label="Skill Match" value={result.skillMatchPercentage} suffix="%" />
                <ScoreCard label="Grammar Issues" value={result.grammarIssues} />
                <ScoreCard label="Tone" value={result.toneAnalysis} />
              </div>
            </div>

            {/* Skills */}
            <div className="grid md:grid-cols-2 gap-6">
              <div className="p-4 border border-border rounded-lg">
                <h3 className="font-mono text-[10px] text-primary uppercase tracking-widest mb-3">
                  Matched Skills
                </h3>
                <div className="flex flex-wrap gap-1">
                  {result.matchedSkills.map((s) => (
                    <span key={s} className="px-2 py-0.5 bg-primary/10 text-primary text-xs rounded font-mono">
                      {s}
                    </span>
                  ))}
                </div>
              </div>
              <div className="p-4 border border-border rounded-lg">
                <h3 className="font-mono text-[10px] text-destructive uppercase tracking-widest mb-3">
                  Missing Skills
                </h3>
                <div className="flex flex-wrap gap-1">
                  {result.missingSkills.map((s) => (
                    <span key={s} className="px-2 py-0.5 bg-destructive/10 text-destructive text-xs rounded font-mono">
                      {s}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Market Demand */}
            <div className="p-4 bg-secondary/50 rounded-lg border border-border">
              <h3 className="font-mono text-[10px] text-muted-foreground uppercase tracking-widest mb-2">
                Market Demand Analysis
              </h3>
              <p className="text-sm">{result.marketDemand}</p>
            </div>

            {/* Suggestions */}
            <div className="p-4 border border-dashed border-border rounded-lg">
              <h3 className="font-mono text-[10px] text-primary uppercase tracking-widest mb-3">
                Improvement Suggestions
              </h3>
              <ul className="space-y-2">
                {result.suggestions.map((s, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <span className="text-primary mt-0.5">•</span>
                    {s}
                  </li>
                ))}
              </ul>
            </div>

            {/* Navigation buttons */}
            <div className="flex flex-wrap items-center gap-4 pt-6 border-t border-border">
              <Button onClick={handleDownload} variant="outline" className="gap-2">
                <Download className="size-4" />
                Download Report
              </Button>
              <Link to="/interview">
                <Button className="gap-2">
                  <MessageSquare className="size-4" />
                  Interview Questions Generator
                </Button>
              </Link>
              <Link to="/">
                <Button variant="outline" className="gap-2">
                  <Home className="size-4" />
                  Home
                </Button>
              </Link>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ResumeAnalyzer;
